spring:
    rabbitmq:
        password: ${RABBITMQ_PASSWORD}
        username: ${RABBITMQ_USERNAME}
        host: ${RABBITMQ_HOST}
        virtual-host: ${RABBITMQ_VHOST}
logging:
    level:
        root: trace